### ISSUE TITLE
Database does not initialize on first install via docker compose

### ISSUE THREAD

**Issue by Bkoltz** [SolidInvoice/SolidInvoice#1648]
I attempted to install SolidInvoice using the Docker Compose file from GitHub on TrueNAS Scale (Electric Eel). While the application starts and runs fine, the database fails to initialize during the first install.
When I navigate to the assigned IP and port in my browser, I only see a blank white screen—there's no prompt to create the database. I copied the Compose file, making only minor adjustments to the port and volume paths.
I suspect I might be missing some required environment variables. Any insights or assistance would be greatly appreciated!

Docker Compose File:

```yaml
services:
  app:
    depends_on:
      - db
    environment:
      SOLIDINVOICE_DATABASE_DRIVER: pdo_mysql
      SOLIDINVOICE_DATABASE_HOST: db
      SOLIDINVOICE_DATABASE_NAME: solidinvoice
      SOLIDINVOICE_DATABASE_PASSWORD: sdfgsdfgasdjhjlgghjsdfg
      SOLIDINVOICE_DATABASE_PORT: 3306
      SOLIDINVOICE_DATABASE_USER: root
    image: solidinvoice/solidinvoice:latest
    ports:
      - '8766:8765'
    restart: always
    volumes:
      - /mnt/Share/Apps/Solid_Invoice/Appdata:/etc/solidinvoice
  db:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: solidinvoice
    image: mysql:8.0
    restart: always
    volumes:
      - /mnt/Share/Apps/Solid_Invoice/Database:/var/lib/mysql
volumes:
  app_data: Null
  db_data: Null
```

DB logs:
```
2025-04-30 13:04:34.921353+00:002025-04-30T13:04:34.920776Z 0 [ERROR] [MY-010119] [Server] Aborting
2025-04-30 13:04:34.921408+00:002025-04-30T13:04:34.920924Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.42)  MySQL Community Server - GPL.
2025-04-30 13:05:35.974166+00:002025-04-30 13:05:35+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.42-1.el9 started.
2025-04-30 13:05:36.197767+00:002025-04-30 13:05:36+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2025-04-30 13:05:36.208575+00:002025-04-30 13:05:36+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.42-1.el9 started.
2025-04-30 13:05:36.411516+00:002025-04-30 13:05:36+00:00 [Note] [Entrypoint]: Initializing database files
2025-04-30 13:05:36.424734+00:002025-04-30T13:05:36.421725Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2025-04-30 13:05:36.424799+00:002025-04-30T13:05:36.421844Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.42) initializing of server in progress as process 80
2025-04-30 13:05:36.424825+00:002025-04-30T13:05:36.424480Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
2025-04-30 13:05:36.424847+00:002025-04-30T13:05:36.424489Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
2025-04-30 13:05:36.425145+00:002025-04-30T13:05:36.424539Z 0 [ERROR] [MY-010119] [Server] Aborting
2025-04-30 13:05:36.425190+00:002025-04-30T13:05:36.424665Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.42)  MySQL Community Server - GPL.
2025-04-30 13:06:37.320956+00:002025-04-30 13:06:37+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.42-1.el9 started.
2025-04-30 13:06:37.584193+00:002025-04-30 13:06:37+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2025-04-30 13:06:37.595968+00:002025-04-30 13:06:37+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.42-1.el9 started.
2025-04-30 13:06:37.811014+00:002025-04-30 13:06:37+00:00 [Note] [Entrypoint]: Initializing database files
2025-04-30 13:06:37.826411+00:002025-04-30T13:06:37.823388Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2025-04-30 13:06:37.826456+00:002025-04-30T13:06:37.823515Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.42) initializing of server in progress as process 80
2025-04-30 13:06:37.826472+00:002025-04-30T13:06:37.826182Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
2025-04-30 13:06:37.826486+00:002025-04-30T13:06:37.826191Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
2025-04-30 13:06:37.826817+00:002025-04-30T13:06:37.826245Z 0 [ERROR] [MY-010119] [Server] Aborting
2025-04-30 13:06:37.826852+00:002025-04-30T13:06:37.826384Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.42)  MySQL Community Server - GPL.
2025-04-30 13:07:38.819362+00:002025-04-30 13:07:38+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.42-1.el9 started.
2025-04-30 13:07:39.048173+00:002025-04-30 13:07:39+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2025-04-30 13:07:39.060158+00:002025-04-30 13:07:39+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.42-1.el9 started.
2025-04-30 13:07:39.274160+00:002025-04-30 13:07:39+00:00 [Note] [Entrypoint]: Initializing database files
2025-04-30 13:07:39.289686+00:002025-04-30T13:07:39.286603Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2025-04-30 13:07:39.289761+00:002025-04-30T13:07:39.286729Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.42) initializing of server in progress as process 80
2025-04-30 13:07:39.289779+00:002025-04-30T13:07:39.289398Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
2025-04-30 13:07:39.289800+00:002025-04-30T13:07:39.289407Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
2025-04-30 13:07:39.290086+00:002025-04-30T13:07:39.289460Z 0 [ERROR] [MY-010119] [Server] Aborting
2025-04-30 13:07:39.290122+00:002025-04-30T13:07:39.289614Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.42)  MySQL Community Server - GPL.
```

**Comment by pierredup** [comment]
The error I'm seeing in the logs are `the data directory has files in it. Aborting.`.

This means your `/mnt/Share/Apps/Solid_Invoice/Database` directory is most likely not empty or has other files inside it. You need to mount an empty directory in the DB container	for the database files.

> When I navigate to the assigned IP and port in my browser, I only see a blank white screen

Currently the application will only work when using `127.0.0.1:<port>` in the browser. This is a bug that should be fixed in the next patch release

**Comment by Bkoltz** [comment]
I deleted the dataset where I had the storage and recreated it, which worked. Not sure why it did that, but thank you. Do you by chance know when the next patch release will be roughly?

**Comment by pierredup** [comment]
Version [2.3.3 has just been released](https://github.com/SolidInvoice/SolidInvoice/releases/tag/2.3.3). The docker images should be updated within the next few hours. If you experience any issues with the latest version, please feel free to re-open this.

**Comment by mariushosting** [comment]
> Version [2.3.3 has just been released](https://github.com/SolidInvoice/SolidInvoice/releases/tag/2.3.3). The docker images should be updated within the next few hours. If you experience any issues with the latest version, please feel free to re-open this.

If I select a database from the list I always get error 500. No matter what I do. Fresh installation using version 2.3.3 

![Image](https://github.com/user-attachments/assets/6fa02cef-7725-43be-b871-300e1fcc80b1)

**Comment by Bkoltz** [comment]
@pierredup The update resolved my previous issues; however, I encountered a problem when creating quotes and invoices—the program would freeze. I restarted the container, but upon restarting, it prompted me to set everything up from scratch, as if it had completely lost the database.

![Image](https://github.com/user-attachments/assets/3cbf0867-9629-42c3-bc89-1c5db6bd5cd7)

**Comment by pierredup** [comment]
> upon restarting, it prompted me to set everything up from scratch, as if it had completely lost the database.

Are there anything in your `/mnt/Share/Apps/Solid_Invoice/Appdata` directory? This should contain some configuration files, that should be persisted between restarts, which means it would keep the same config for the DB when the container restarts

**Comment by pierredup** [comment]
> upon restarting, it prompted me to set everything up from scratch, as if it had completely lost the database.

Okay I see this is a bug, it should be fixed in the next patch release with #1660

**Comment by pierredup** [comment]
> I encountered a problem when creating quotes and invoices—the program would freeze

Will have a look at this as well

**Comment by Bkoltz** [comment]
@pierredup, there is nothing in the AppData directory. Let me know when the patch is released, and I can test it out. The issue with the creating quotes and invoices resulting in the app freezing could also be related to the fact that there is nothing in the Appdata directory if it can't correctly persist the storage.

**Comment by pierredup** [comment]
Version 2.3.4 has been released and should fix all the issues mentioned. Please let me know if you experience any additional errors

**Comment by hglatham** [comment]
It still doesn't work, creating an invoice freezes as before.

**Comment by pierredup** [comment]
@hglatham can you maybe expand a bit more on what you mean that it freezes when creating an invoice?

* Do you have any email configurations set up?
* Does it happen when creating an invoice as draft, creating and sending the invoice or creating the invoice without sending it?
* Does the page just koad continuously and times out after a while?
* Are there any noticable errors reported in the logs?
* Does it only happen when running the application using docker?

Maybe adding a video recording of the process as well can be helpful.

**Comment by mariushosting** [comment]
I'm unable to use mysql or postgres after add the password the password disappear
in the latest version 2.3.4

Error An exception occurred in the driver: SQLSTATE[HY000] [1524] Plugin 'mysql_native_password' is not loaded

SQLITE works very well.

**Comment by Bkoltz** [comment]
@pierredup I still have the same issue; however, the embedded database problem was solved. To replicate the issue of the program becoming unresponsive after creating a quote for me was: Create user (only added the necessary fields) -> set the new test user as the person for the quote, type words in the description, terms, and 50.00 in the amount -> save Quote -> error:

![Image](https://github.com/user-attachments/assets/9ac1ab59-1525-42c9-8083-33ad7e40a1db)

but I can save a quote with the same quote with only changing the $$ value by leaving it as 0.00. 
Moral of the story the error only occurs when a non-default value is entered into the price box.

**Comment by hglatham** [comment]
Do you have any email configurations set up?
Yes, SMTP 
Does it happen when creating an invoice as draft, creating and sending the invoice or creating the invoice without sending it?
Creating an Invoice as draft.
Does the page just koad continuously and times out after a while?
Synology message > Sorry, the pagey ou are looking for is not found. I notice that I can put a single numeral in the price field and it will populate the Total field but two or more digits and it returns the error.
Are there any noticable errors reported in the logs?
Nothing in the logs.
Does it only happen when running the application using docker?
I have only tried to use it in a docker.

**Comment by pierredup** [comment]
> I'm unable to use mysql or postgres after add the password the password disappear

@mariushosting Thanks, this should be fixed with #1666. 

> Error An exception occurred in the driver: SQLSTATE[HY000] [1524] Plugin 'mysql_native_password' is not loaded

I think this might be an issue with the MySQL setup you are using. What version of MySQL are you using? The `mysql_native_password` plugin has been removed in MySQL 9.0, so maybe try with MySQL 8.3 (I suspect 8.4 might also have the same issue)

**Comment by pierredup** [comment]
> > Do you have any email configurations set up?
> Yes, SMTP

@hglatham It might be possible that the SMTP connection fails, which is why the system just hangs and times out with an error after a while. Can you maybe check with a fresh installation with no email configuration set up?

**Comment by mariushosting** [comment]
> > I'm unable to use mysql or postgres after add the password the password disappear
> 
> [@mariushosting](https://github.com/mariushosting) Thanks, this should be fixed with [#1666](https://github.com/SolidInvoice/SolidInvoice/pull/1666).
> 
> > Error An exception occurred in the driver: SQLSTATE[HY000] [1524] Plugin 'mysql_native_password' is not loaded
> 
> I think this might be an issue with the MySQL setup you are using. What version of MySQL are you using? The `mysql_native_password` plugin has been removed in MySQL 9.0, so maybe try with MySQL 8.3 (I suspect 8.4 might also have the same issue)

Yep mysql 8.
Thanks!

**Comment by mariushosting** [comment]
> > > Do you have any email configurations set up?
> > > Yes, SMTP
> 
> [@hglatham](https://github.com/hglatham) It might be possible that the SMTP connection fails, which is why the system just hangs and times out with an error after a while. Can you maybe check with a fresh installation with no email configuration set up?

I confirm there is no issue with SMTP on my end.

**Comment by hglatham** [comment]
I'm afraid that has not made any difference. I have reinstalled and followed your suggestion to not set up SMTP and it is still not possible to enter more than the value of 1 > 9 in the price field. It returns the 404 error after that.

**Comment by Bkoltz** [comment]
> It might be possible that the SMTP connection fails, which is why the system just hangs and times out with an error after a while. Can you maybe check with a fresh installation with no email configuration set up?

From what I mentioned before, it was from a fresh install with no email config set up. I only inputted the necessary data to get started and then tested the method which resulted in the same connection timeout.

**Comment by pierredup** [comment]
Thanks for the update. I'm still not able to replicate the error, so would need to investigate it a bit more.

**Comment by Bkoltz** [comment]
@pierredup Here is a video of what I am doing to get the error consistently. Solid Invoice installed via Docker on the latest release with embedded database.

**Comment by Bkoltz** [comment]
@pierredup Here is a video of what I am doing to get the error consistently. Solid Invoice installed via Docker on the latest release with embedded database.
https://1drv.ms/v/c/d9ccda2b40bf91f9/EYg8NB5cMkBKgjEy6qKeOdkBmApGyVuDZft7qInsVMieOw?e=z8Ozzq

**Comment by pierredup** [comment]
Version [2.3.5 has just been released](https://github.com/SolidInvoice/SolidInvoice/releases/tag/2.3.5). Not sure if it will fix the hanging when creating an invoice, but worth a try. It also fixes the following issue:

> I'm unable to use mysql or postgres after add the password the password disappear

**Comment by mariushosting** [comment]
> Version [2.3.5 has just been released](https://github.com/SolidInvoice/SolidInvoice/releases/tag/2.3.5). Not sure if it will fix the hanging when creating an invoice, but worth a try. It also fixes the following issue:
> 
> > I'm unable to use mysql or postgres after add the password the password disappear

I can confirm now that PostgreSQL works perfectly and MySQL too. Only the favicon on the browser is not visible anymore only on **https** if you use postgres or mysql.

**Comment by Bkoltz** [comment]
@pierredup There is still the same issue when trying to create a quote or invoice. It only happens when I try to type in a number into the price field. could this be caused by having a wrong pointer or how it is stored?

**Comment by pierredup** [comment]
The error when creating quotes/invoices with a positive value should now be resolved in the [2.3.6 Release](https://github.com/SolidInvoice/SolidInvoice/releases/tag/2.3.6)
